- core/rocketjoe/python_sandbox/detail/jupyter/pykernel.hpp
- core/rocketjoe/python_sandbox/detail/jupyter/session.hpp
- core/rocketjoe/python_sandbox/source/detail/jupyter/pykernel.cpp
- core/rocketjoe/python_sandbox/source/detail/jupyter/session.cpp
> Implement pickle for ipyparallel

- components/ql/ql_param_statement.cpp
- components/ql/ql_param_statement.hpp
- components/ql/statements.hpp
- components/sql/CMakeLists.txt
- components/sql/parser.cpp
- components/sql/parser/base/parse_error.hpp
- components/sql/parser/base/parser_mask.cpp
- components/sql/parser/base/parser_mask.hpp
- components/sql/parser/base/parser_where.cpp
- components/sql/parser/base/parser_where.hpp
- components/sql/parser/database/impl/parser_database_create.cpp
- components/sql/parser/database/impl/parser_database_drop.cpp
- components/sql/parser/insert/impl/parser_insert_into.cpp
- components/sql/parser/select/impl/parser_select_base.cpp
- components/sql/parser/select/impl/parser_select_base.hpp
- components/sql/parser/select/parser_select.cpp
- components/sql/parser/select/parser_select.hpp
- components/sql/test/CMakeLists.txt
- components/sql/test/test_parser_select.cpp
- services/dispatcher/session.cpp
> SQL-parser: SELECT FROM WHERE

- components/ql/statements/delete_many.cpp
- components/ql/statements/delete_many.hpp
- components/sql/CMakeLists.txt
- components/sql/lexer/lexer.cpp
- components/sql/lexer/lexer.hpp
- components/sql/parser.cpp
- components/sql/parser/base/parser_where.cpp
- components/sql/parser/delete/impl/parser_delete_base.cpp
- components/sql/parser/delete/impl/parser_delete_base.hpp
- components/sql/parser/delete/parser_delete.cpp
- components/sql/parser/delete/parser_delete.hpp
- components/sql/test/CMakeLists.txt
- components/sql/test/test_parser_delete.cpp
> SQL-parser: DELETE FROM WHERE

- components/document/wrapper_value.hpp
- components/expressions/compare_expression.cpp
- components/ql/statements/update_many.cpp
- components/ql/statements/update_many.hpp
- components/sql/CMakeLists.txt
- components/sql/lexer/token.cpp
- components/sql/lexer/token.hpp
- components/sql/parser.cpp
- components/sql/parser/base/parse_error.hpp
- components/sql/parser/base/parser_mask.cpp
- components/sql/parser/base/parser_set.cpp
- components/sql/parser/base/parser_set.hpp
- components/sql/parser/update/impl/parser_update_base.cpp
- components/sql/parser/update/impl/parser_update_base.hpp
- components/sql/parser/update/parser_update.cpp
- components/sql/parser/update/parser_update.hpp
- components/sql/test/CMakeLists.txt
- components/sql/test/test_parser_delete.cpp
- components/sql/test/test_parser_update.cpp
> SQL-parser: UPDATE SET WHERE

- components/sql/CMakeLists.txt
- components/sql/parser/base/parse_error.hpp
- components/sql/parser/base/parser_mask.cpp
- components/sql/parser/base/parser_mask.hpp
- components/sql/parser/base/parser_orderby.cpp
- components/sql/parser/base/parser_orderby.hpp
- components/sql/parser/select/impl/parser_select_base.cpp
- components/sql/test/test_parser_select.cpp
- integration/cpp/test/test_collection_sql.cpp
- services/collection/CMakeLists.txt
- services/collection/planner/create_plan.cpp
- services/collection/planner/impl/create_plan_sort.cpp
- services/collection/planner/impl/create_plan_sort.hpp
Parsing simple queries with order by
> SQL-parser: ORDER BY

- components/sql/CMakeLists.txt
- components/sql/lexer/token.cpp
- components/sql/parser/select/impl/parser_select_base.cpp
- components/sql/parser/select/impl/parser_select_fields.cpp
- components/sql/parser/select/impl/parser_select_fields.hpp
- components/sql/parser/select/impl/parser_select_from.cpp
- components/sql/parser/select/impl/parser_select_from.hpp
- components/sql/parser/select/impl/parser_select_without_from.cpp
- components/sql/parser/select/impl/parser_select_without_from.hpp
- components/sql/parser/select/parser_select.cpp
- components/sql/test/test_parser_select.cpp
Add parse:
* select FIELDS from ...
* select CONSTANT as title;
* select CONSTANT;
> SQL-parser: fields in select

- components/sql/CMakeLists.txt
- components/sql/lexer/token.cpp
- components/sql/lexer/token.hpp
- components/sql/parser/base/parse_error.hpp
- components/sql/parser/base/parser_groupby.cpp
- components/sql/parser/base/parser_groupby.hpp
- components/sql/parser/base/parser_orderby.cpp
- components/sql/parser/select/impl/parser_select_fields.cpp
- components/sql/parser/select/impl/parser_select_fields.hpp
- components/sql/parser/select/impl/parser_select_from.cpp
- components/sql/parser/select/impl/parser_select_without_from.cpp
- components/sql/test/test_parser_select.cpp
- integration/cpp/test/test_collection_sql.cpp
- services/collection/CMakeLists.txt
- services/collection/planner/create_plan.cpp
- services/collection/planner/impl/create_plan_group.cpp
- services/collection/planner/impl/create_plan_group.hpp
* parsing simple queries with group by
* detecting syntax errors
* detecting different fields in select and group by
* executing group by queries
* add tests
#207
> SQL-parser: GROUP BY

- components/logical_plan/CMakeLists.txt
- components/logical_plan/forward.hpp
- components/logical_plan/node_create_collection.cpp
- components/logical_plan/node_create_collection.hpp
- components/logical_plan/node_create_database.cpp
- components/logical_plan/node_create_database.hpp
- components/logical_plan/node_drop_collection.cpp
- components/logical_plan/node_drop_collection.hpp
- components/logical_plan/node_drop_database.cpp
- components/logical_plan/node_drop_database.hpp
- components/translator/ql_translator.cpp
- components/translator/test/test_logical_plan.cpp
- integration/cpp/test/test_collection_sql.cpp
- integration/cpp/wrapper_dispatcher.cpp
- integration/cpp/wrapper_dispatcher.hpp
- services/dispatcher/dispatcher.cpp
- services/dispatcher/dispatcher.hpp
- services/dispatcher/route.hpp
- services/memory_storage/memory_storage.cpp
- services/memory_storage/memory_storage.hpp
- services/memory_storage/result.cpp
- services/memory_storage/result.hpp
- services/memory_storage/route.hpp
* add method execute_plan (input: logical plan)
* remove method execute_ql (ql convert into logic_plan dispatcher)
> Make method execute_plan into memory_storage

- services/collection/collection.cpp
> Fix python tests test_collection

- components/sql/parser/delete/impl/parser_delete_base.cpp
- components/sql/parser/update/impl/parser_update_base.cpp
- integration/cpp/wrapper_dispatcher.cpp
- services/collection/planner/impl/create_plan_group.cpp
- services/dispatcher/dispatcher.cpp
- services/memory_storage/memory_storage.cpp
I tried to add asserts for holds alternative types, that had been written about it the issue #264.
https://github.com/duckstax/ottergon/issues/264.
> asserts for debug to develop

- .gitignore
- scripts/CI/run-check-formatting.sh
- scripts/README.md
- scripts/bootstrap.sh
- scripts/format.sh
- scripts/git-hooks/pre-commit.sh.in
- scripts/git-hooks/setup-git-hooks.sh
- scripts/tools/code-fromat.py
- scripts/tools/common.py
* add fromatting script
* add precommit hooks
* add CI check script
> Add formmating

- .github/workflows/ubuntu-20-04-sanitizer.yaml
- CMakeLists.txt
- cmake/FindASan.cmake
- cmake/FindSanitizers.cmake
- cmake/address_sanitizer.cmake
- docker/Dockerfile-ubuntu-20
- docker/Dockerfile-ubuntu-20-address-sanitizer
Add address sanitaizers and CI check
> Add address sanitizer

- services/collection/collection.cpp
- services/collection/collection.hpp
- services/collection/operators/operator.cpp
- services/collection/operators/operator.hpp
- services/memory_storage/memory_storage.cpp
Only root operator will be able to write anything to cursor_storage in collection_t now
> Multicollection physical plan bugfix

- README.md
- components/ql/join/join_types.h
- components/sql/parser/select/impl/parser_select_from.cpp
- components/sql/test/test_parser_join.cpp
- integration/cpp/test/test_join.cpp
- integration/python/otterbrix/setup.py
- services/collection/operators/operator_join.cpp
- services/collection/operators/operator_join.hpp
- services/collection/planner/impl/create_plan_join.cpp
Complete join functionality, excluding join methods
> Working Join

- components/document/document.cpp
- components/document/document.hpp
- components/sql/parser/select/impl/parser_select_from.cpp
- integration/cpp/test/test_join.cpp
- services/collection/operators/operator_join.cpp
Combining documents moved to a static method of document_t
> Combine documents refactoring

- integration/c/main.cpp
- integration/c/otterbrix.h
- integration/csharp/src/Duckstax.Otterbrix/OtterbrixWrapper.cs
- integration/csharp/tests/Duckstax.Otterbrix.Tests/WrapperTest.cs
> CSharp database/collection SQL syntax added

- .github/workflows/manylinux2014.yml
> Publish to PyPi on tag push

- README.md
- components/document/document.cpp
- components/document/document.hpp
- components/document/impl/element.cpp
- components/document/impl/element.hpp
- components/document/impl/tape_builder.hpp
- components/document/impl/tape_ref.cpp
- components/document/impl/tape_ref.hpp
- components/document/value.cpp
- components/log/CMakeLists.txt
- components/types/CMakeLists.txt
- components/types/logical_value.cpp
- components/types/logical_value.hpp
- components/types/physical_value.cpp
- components/types/physical_value.hpp
- components/types/tests/test_types.cpp
- components/types/types.cpp
- components/types/types.hpp
- integration/python/otterbrix/setup.py
- services/disk/index_disk.cpp
Preparation for column storage:
* physical_type boolean value is no longer encoded into enum
* complex logical types added (columns require a concrete implementation)
> Addition of complex types

- core/file/file_handle.cpp
- core/file/file_handle.hpp
- core/file/file_system.hpp
- core/file/local_file_system.cpp
- core/file/local_file_system.hpp
- core/file/virtual_file_system.cpp
- core/file/virtual_file_system.hpp
* file open flags now constexp
* trim function added
> Filesystem trim function added

- components/base/collection_full_name.hpp
- components/logical_plan/CMakeLists.txt
- components/logical_plan/forward.hpp
- components/logical_plan/node_data.cpp
- components/logical_plan/node_data.hpp
- components/physical_plan/CMakeLists.txt
- components/physical_plan/collection/operators/operator.hpp
- components/physical_plan/collection/operators/operator_data.cpp
- components/physical_plan/collection/operators/operator_data.hpp
- components/physical_plan/collection/operators/operator_join.cpp
- components/physical_plan/collection/operators/operator_raw_data.cpp
- components/physical_plan/collection/operators/operator_raw_data.hpp
- components/physical_plan_generator/CMakeLists.txt
- components/physical_plan_generator/create_plan.cpp
- components/physical_plan_generator/impl/create_plan_data.cpp
- components/physical_plan_generator/impl/create_plan_data.hpp
- components/planner/planner.cpp
- components/ql/CMakeLists.txt
- components/ql/ql_statement.hpp
- components/ql/statements/raw_data.cpp
- components/ql/statements/raw_data.hpp
- integration/cpp/test/test_collection_ql.cpp
- services/collection/executor.cpp
- services/memory_storage/memory_storage.cpp
Added a basic functionality to do operations on data without creating a collection inside OtterBrix
> support for raw data in ql_statement

- components/logical_plan/node.cpp
- components/logical_plan/node.hpp
- components/physical_plan/CMakeLists.txt
- components/physical_plan/collection/operators/aggregate/operator_aggregate.cpp
- components/physical_plan/collection/operators/aggregate/operator_avg.cpp
- components/physical_plan/collection/operators/aggregate/operator_count.cpp
- components/physical_plan/collection/operators/aggregate/operator_max.cpp
- components/physical_plan/collection/operators/aggregate/operator_min.cpp
- components/physical_plan/collection/operators/aggregate/operator_sum.cpp
- components/physical_plan/collection/operators/aggregation.cpp
- components/physical_plan/collection/operators/merge/operator_and.cpp
- components/physical_plan/collection/operators/merge/operator_or.cpp
- components/physical_plan/collection/operators/operator_group.cpp
- components/physical_plan/collection/operators/operator_group.hpp
- components/physical_plan/collection/operators/operator_match.cpp
- components/physical_plan/collection/operators/operator_match.hpp
- components/physical_plan/collection/operators/operator_sort.cpp
- components/physical_plan_generator/impl/create_plan_aggregate.cpp
- components/physical_plan_generator/impl/create_plan_group.cpp
- components/physical_plan_generator/impl/create_plan_match.cpp
- components/planner/planner.cpp
- components/planner/planner.hpp
- components/ql/aggregate.cpp
- components/ql/aggregate.hpp
- integration/cpp/test/test_collection_ql.cpp
- scripts/format.sh
Aggregate now can be applied after other operators, including raw_data
> Raw data aggregate support

- components/document/document.cpp
- components/physical_plan/collection/operators/sort/sort.hpp
- components/sql/test/test_function.cpp
- components/sql/test/test_join.cpp
- components/sql/transformer/impl/transform_select.cpp
- integration/cpp/test/test_join.cpp
Turns out, previous join parsing implementation skiped group, match and sort
* some sort edgecases fixed
> Group, sort, match support for join

- components/sql/test/test_create_drop.cpp
- components/sql/transformer/impl/transform_index.cpp
fix and tests for parsing uuid.database.schema.table format
> Create index parsing fix

- components/physical_plan/base/operators/operator_raw_data.cpp
fixed capacity initialization in operator_data
> Table operator_data fix
